### ISSUE TITLE
Error in console when you walk on game field.

### ISSUE THREAD

**Issue by Floodo** [CraZyRc/WhackaMole#17]
### /version

```txt
This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
You are running the latest version
Previous version: git-Paper-78 (MC: 1.19)
```

### /version WhackaMole

```txt
WhackaMole version 2.2.0
```

### Log file

https://pastebin.com/bT3Dyy8R

### config.yml

https://pastebin.com/iGUzv58q

### <Gamename>.yml

https://pastebin.com/B08A8esu

### Description

I just jump on game field as OP player (it happends also for no OP player). One empty slot in hand. Error happends just at the moment when the game gives you axe.

**Comment by CraZyRc** [comment]
Issue is for 1.19 till 1.19.2, it's fixed in 1.19.3
Given it's only in these versions we won't fix it (at least not now).

also, update your config dude ;)
