### ISSUE TITLE
Support for older versions?

### ISSUE THREAD

**Issue by CraZyRc** [CraZyRc/WhackaMole#2]
### I confirm that I have ...

- [X] ...tried the latest build to make sure my feature doesn't exist already.
- [X] ...checked the realism of my feature and i think it can be executed.
- [X] ...checked other existing issues for my feature request.

### Description

Should I make versions for older Minecraft versions?

It's not a lot of work but it's tedious and I wonder if you guys even want/need that.

So reply in the comments, should I add releases for older versions, and if so, which versions?

**Comment by Floodo** [comment]
The 1.17 version would be nice :)

**Comment by CraZyRc** [comment]
> The 1.17 version would be nice :)

Consider it done :) 
Will release tomorrow

**Comment by CraZyRc** [comment]
> The 1.17 version would be nice :)

https://github.com/CraZyRc/WhackaMole/releases/tag/1.17.1

Here you go, 1.17 will be taken in account with updates so check out the 1.17 tag for updates :)
