### ISSUE TITLE
SOLVED!!!    unknown world ?????

### ISSUE THREAD

**Issue by K4o0s2** [CraZyRc/WhackaMole#21]
### /version

```txt
> version
[00:30:34 INFO]: Checking version, please wait...
[00:30:34 INFO]: Current: git-Purpur-2166 (MC: 1.20.4)*
Previous: git-Purpur-2165 (MC: 1.20.4)
* You are running the latest version
>
```

### /version WhackaMole

```txt
2.3.0
```

### Log file

https://pastebin.com/EB9ZbCj3

### config.yml

https://pastebin.com/DyrDiDsf

### <Gamename>.yml

https://pastebin.com/0T4u8ERe

### Description

Good evening.

As I was mentioning on the Spigot page...
The only thing I have done is this:

Download the plugin.
Put it in the server's plugins folder and start the server.
Change "SCOREBOARD" to "VAULT" in the generated config.yml file.
Restart the server.
At this point, I create the game "Topo" and put it in my lobby, and everything works correctly.
But when I restart the server, it throws that error and I don't understand why.

I hope you can replicate it. It doesn't make sense that it works correctly when initially loaded and then not anymore.

I'm sure I'm doing something wrong, but I don't know what it is.

Greetings from Spain.

**Comment by CraZyRc** [comment]
Hmm thanks for the full info log and clear explanation. I'll look into this asap

**Comment by GnarLito** [comment]
@K4o0s2 could you provide the full logs from startup till crash.

It looks like we have a race condition between the world loading and the loading of the lobby game.

Hoe is the lobby managed? Is this a normal minecraft world is is it loaded from another plugin?

**Comment by GnarLito** [comment]
@CraZyRc we may need to look at storing the streak location differently to combat this issue

**Comment by K4o0s2** [comment]
> @K4o0s2¿Podría proporcionar los registros completos desde el inicio hasta el fallo?
> 
> Parece que tenemos una condición de carrera entre la carga del mundo y la carga del juego del lobby.
> 
> ¿Cómo se gestiona el lobby? ¿Es este un mundo normal de Minecraft? ¿Se carga desde otro complemento?

Sorry for the delay, but these have been very long and tough days.

I think there wouldn't be a problem in dumping the server boot log. Give me a moment because I have the kids connected, and if I bring down the server now, they'll kill me. Hahahaha. However, I warn you that it will be long. I have about 70 plugins installed.

**Comment by CraZyRc** [comment]
> > @K4o0s2¿Podría proporcionar los registros completos desde el inicio hasta el fallo?
> > Parece que tenemos una condición de carrera entre la carga del mundo y la carga del juego del lobby.
> > ¿Cómo se gestiona el lobby? ¿Es este un mundo normal de Minecraft? ¿Se carga desde otro complemento?
> 
> Sorry for the delay, but these have been very long and tough days.
> 
> I think there shouldn't be a problem dumping the server boot log. Give me a moment because I have the kids connected and if I shut down the server now, they'll kill me. Hahaha However, I warn you that it will be long. I have about 70 plugins installed.
> 
> I've changed some things to see if it works or not. The previous lobby world is now called minigames.
> 
> So, the current lobby is a regular world controlled by the DeluxeHub plugin.
> 
> The worlds are connected through Multiverse Core.
> 
> I have a Raspberry Pi with Velocity. Behind it, I have a Linux server running Ubuntu handling the rest. The main structure is an auth plugin, and after that, it takes us to the lobby world. There are some NPCs there, along with our navigation bar that takes us to the main world and the minigames (where I'm currently testing the Whack-A-Mole).
> 
> I'll run the relevant tests, and as soon as they let me, I'll restart it twice and see if the issue repeats. I'll give you more details in a few hours.

Sorry for my late response, would it be able for you to send the log? I think i know the issue, but i need to verify and only your server log can verify this 🙃

Graciass in advance and good luck with the kids 😊

**Comment by CraZyRc** [comment]
@K4o0s2 , does the new version fix your issue? Then I know if I can close this thread 🙃

**Comment by K4o0s2** [comment]
Hello!!! Sorry. I haven't been able to check anything for a while. I've downloaded and tested the latest version, and it works perfectly now. You've done a great job. I appreciate it a lot (and my son even more xDD).

I am naturally curious. I have some knowledge of Java, and that leads me to ask... What was wrong? I know it's none of my business, but I'm curious.

Best regards and a million thanks for everything.

**Comment by CraZyRc** [comment]
> Hello!!! Sorry. I haven't been able to check anything for a while. I've downloaded and tested the latest version, and it works perfectly now. You've done a great job. I appreciate it a lot (and my son even more xDD).
> 
> I am naturally curious. I have some knowledge of Java, and that leads me to ask... What was wrong? I know it's none of my business, but I'm curious.
> 
> Best regards and a million thanks for everything.

In going to be perfectly honest with you, i have 0 clue why it works now 😂

Your issue had to do with world loading, and I think that might be because of a plugin you use (DeluxeHub), which i think controls your world loading.

Did you maybe update that? Because I haven't heard of the issue you had before and I haven't touched the world loading part of the plugin.

But at least it works now and I'm glad your son is happy too!

Let me know if you encounter any other problem and if it's okay with you, I'd like to see your server. I haven't seen any server use the plugin before and I'd love to see it 😊

Could you send the IP address and version of your server?
