### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Floodo** [CraZyRc/WhackaMole#3]
### /version

```txt
This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
```

### /version WhackaMole

```txt
WhackaMole version 1.19.2-v1.3
```

### Log file

https://pastebin.com/sFF4FPJX

### config.yml

https://pastebin.com/xNA0hsuq

### Description

I use on my server Gayser. At the time, I was only one on the server. And only thing that I did, was picking up smelted stone from furnace and placing down stone_bricks and cobblestone. I wasn't near the console, so I could see, what the error mades. But the using of furnace seems to me little weird, so maybe thats it.

**Comment by CraZyRc** [comment]
thanks for the bug post, I'll look into it straight away

**Comment by CraZyRc** [comment]
found the bug, resulted due to right-click outside of the inventory box, will be patched in next version :)
