### ISSUE TITLE
Discord or any support channel

### ISSUE THREAD

**Issue by Floodo** [CraZyRc/WhackaMole#4]
### I confirm that I have ...

- [X] ...tried the latest build to make sure my feature doesn't exist already.
- [X] ...checked the realism of my feature and i think it can be executed.
- [X] ...checked other existing issues for my feature request.

### Description

1. Should be added, because you wouldn't have way too many issue reports simply just for some question. (Discord invite doesn't work on your GitHub -> Rollercraft Discord)
2. Like no need to create GitHub account or just they don't need to complete issue forms for simple question.
3. Some platform, where you can just ask.
4. Discord propably the best (for rooms)

### Code Example

```java
public supportRoom
```

**Comment by CraZyRc** [comment]
The discord link was set to expire after one week, silly me c:

Updated the discord link, it should now work forever :)

**Comment by Floodo** [comment]
ehm, where is the discord link? On your spigot page can't find it, also on front page of GitHub I can't see it .... only when you go to issues section, and than click new issue, and here I can see Rollercraft discord, but I don't have permission to enter :((

**Comment by CraZyRc** [comment]
https://discord.gg/RNhtzvsBGP is the new link :) I've added it to the front page and i totally forgot to change the link in the issues section so I'll change that right away!
